name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
  dist/ocean.gif?color_snake=cyan&color_dots=#1f2937,#2563eb,#3b82f6,#60a5fa,#93c5fd

      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
